/* DN Today — board snapshot.
   Product figures are live as of 2026-09-13.
   Opportunities, lists, and customers are invented examples. */

window.DN_TODAY = {
  asOf: "2026-09-13",
  timezone: "America/New_York",
  productScope:
    "Product is still only the listing popup plus embedded School Explorer and Neighborhood Explorer.",

  assignees: [
    { id: "myles", name: "Myles", role: "Marketing — makes the calls" },
    { id: "bill", name: "Bill", role: "Runs the company" },
    { id: "dn", name: "Dream Neighborhood", role: "Product / support" },
  ],

  grades: {
    A: "Ready to talk",
    B: "Maybe later",
    C: "Not yet",
  },

  product: {
    id: "product",
    title: "Product",
    dataKind: "live",
    status: "ok",
    glance: "v269 shipped last night · QA none",
    environments: [
      {
        id: "nh-prod",
        name: "Neighborhood production",
        version: "v269",
        card: "Shipped last night · PR 125",
        note: "Shipped last night from main. PR 125.",
        tone: "ok",
      },
      {
        id: "nh-staging",
        name: "Neighborhood staging",
        version: "v753",
        card: "Same ship as production",
        note: "Same Explorer chip scroll, Data Shown, and narrow footer that went to production.",
        tone: "ok",
      },
      {
        id: "schools-prod",
        name: "Schools production",
        version: "v270",
        card: "Not in last night’s Neighborhood ship",
        note: "Not in last night’s Neighborhood ship. Holding steady.",
        tone: "ok",
      },
    ],
    qa: {
      id: "qa",
      action: "none",
      detail:
        "Overnight QA Action: none. Log noise and a Walk & Bike watch only. No new buyer breakage.",
      tone: "ok",
    },
    lastShip: {
      id: "last-ship",
      summary: "Chip scroll + admin Data Shown + narrow embed footer",
      detail:
        "PR 125 merged to main and shipped to Neighborhood production as v269. Buyers get chip arrows and grab-to-scroll when tabs overflow, admin Data Shown boxes that match the real tabs, and a visible narrow-embed footer (provided-by, Terms, Privacy, Data sources).",
    },
  },

  customers: {
    id: "customers",
    title: "Customers",
    dataKind: "example",
    status: "watch",
    glance: "Everyone we know",
    directory: [
      {
        id: "west",
        name: "Example Realty — West",
        email: "west@example-realty.test",
        website: "https://west.example-realty.test",
        phone: "(555) 010-2001",
        notes: "Leftover snippet on an old embed key",
        region: "SE",
      },
      {
        id: "piedmont",
        name: "Example Homes — Piedmont",
        email: "piedmont@example-homes.test",
        website: "https://piedmont.example-homes.test",
        phone: "(555) 010-2200",
        notes: "School Explorer snippet missing on the new template",
        region: "SE",
      },
      {
        id: "harbor",
        name: "Example Group — Harbor",
        email: "harbor@example-group.test",
        website: "https://harbor.example-group.test",
        phone: "",
        notes: "Watched the LocalLogic switch video",
        region: "NE",
      },
      {
        id: "lakeside",
        name: "Example Homes — Lakeside",
        email: "lakeside@example-homes.test",
        website: "https://lakeside.example-homes.test",
        phone: "(555) 010-2500",
        notes: "On the LocalLogic list and the School Explorer upgrade list",
        region: "NE",
      },
      {
        id: "oak",
        name: "Example Realty — Oak",
        email: "oak@example-realty.test",
        website: "https://oak.example-realty.test",
        phone: "(555) 010-2600",
        notes: "IDX site has no neighborhood data",
        region: "SE",
      },
      {
        id: "ridge",
        name: "Example Partners — Ridge",
        email: "ridge@example-partners.test",
        website: "https://ridge.example-partners.test",
        phone: "(555) 010-2700",
        notes: "Replied after the LocalLogic video",
        region: "NE",
      },
      {
        id: "candy",
        name: "Example Partner — Candy Lane",
        email: "candy@example-partner.test",
        website: "https://candy.example-partner.test",
        phone: "(555) 010-1000",
        notes: "RealtyCandy leftover branding on three example dashboards",
        region: "SE",
      },
      {
        id: "maple",
        name: "Example Buyer — Maple",
        email: "maple@example-buyer.test",
        website: "",
        phone: "(555) 010-2800",
        notes: "Stuck on the listing popup. Not on an outreach list.",
        region: "SE",
      },
      {
        id: "brook",
        name: "Example Homes — Brook",
        email: "brook@example-homes.test",
        website: "https://brook.example-homes.test",
        phone: "(555) 010-2900",
        notes: "Free School Explorer — replied about upgrading",
        region: "NE",
      },
      {
        id: "summit",
        name: "Example Group — Summit",
        email: "summit@example-group.test",
        website: "https://summit.example-group.test",
        phone: "(555) 010-3000",
        notes: "LocalLogic office, follow-up sent",
        region: "SE",
      },
      {
        id: "pine",
        name: "Example Realty — Pine",
        email: "pine@example-realty.test",
        website: "https://pine.example-realty.test",
        phone: "(555) 010-3100",
        notes: "IDX with no neighborhood data — replied",
        region: "NE",
      },
      {
        id: "vale",
        name: "Example Partners — Vale",
        email: "vale@example-partners.test",
        website: "https://vale.example-partners.test",
        phone: "(555) 010-3200",
        notes: "IDX follow-up sent",
        region: "SE",
      },
      {
        id: "quarry",
        name: "Example Homes — Quarry",
        email: "quarry@example-homes.test",
        website: "https://quarry.example-homes.test",
        phone: "(555) 010-3300",
        notes: "Free School Explorer, no video yet on IDX list",
        region: "NE",
      },
    ],
  },

  lists: {
    id: "lists",
    title: "Lists",
    dataKind: "example",
    status: "watch",
    glance: "3 example lists",
    items: [
      {
        id: "locallogic",
        name: "LocalLogic switch",
        blurb: "Offices using LocalLogic.",
        video: "Switch from LocalLogic — Neighborhood Explorer on your listings",
        members: [
          { id: "west", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "harbor", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "lakeside", videoSent: true, followupSent: true, responded: false, grade: "B", assignee: "" },
          { id: "oak", videoSent: true, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "ridge", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "brook", videoSent: false, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "summit", videoSent: true, followupSent: true, responded: false, grade: "B", assignee: "" },
        ],
      },
      {
        id: "idx",
        name: "IDX with no neighborhood data",
        blurb: "IDX sites missing neighborhood data.",
        video: "Neighborhood data on every IDX listing",
        members: [
          { id: "west", videoSent: true, followupSent: true, responded: true, grade: "B", assignee: "" },
          { id: "piedmont", videoSent: true, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "pine", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "vale", videoSent: true, followupSent: true, responded: false, grade: "B", assignee: "" },
          { id: "quarry", videoSent: false, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "oak", videoSent: true, followupSent: false, responded: false, grade: "C", assignee: "" },
        ],
      },
      {
        id: "schools-upgrade",
        name: "Free School Explorer — upgrade",
        blurb: "Free School Explorer offices that could upgrade.",
        video: "Upgrade from free School Explorer",
        members: [
          { id: "piedmont", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "lakeside", videoSent: true, followupSent: false, responded: false, grade: "B", assignee: "" },
          { id: "candy", videoSent: true, followupSent: true, responded: false, grade: "C", assignee: "" },
          { id: "brook", videoSent: true, followupSent: true, responded: true, grade: "B", assignee: "" },
          { id: "quarry", videoSent: true, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "summit", videoSent: false, followupSent: false, responded: false, grade: "C", assignee: "" },
        ],
      },
    ],
  },

  opportunities: {
    id: "opportunities",
    title: "Opportunities",
    dataKind: "example",
    status: "watch",
    glance: "Talk to people who wrote back",
  },
};
