/* DN Today — board snapshot.
   Product figures are live as of 2026-09-13.
   Views, opportunities, lists, customers, and notes are invented examples. */

window.DN_TODAY = {
  asOf: "2026-09-13",
  timezone: "America/New_York",
  productScope:
    "Product is still only the listing popup plus embedded School Explorer and Neighborhood Explorer.",

  assignees: [
    { id: "myles", name: "Myles", role: "Marketing — makes the calls" },
    { id: "bill", name: "Bill", role: "Runs the company" },
    { id: "dn", name: "Dream Neighborhood", role: "Product / support" },
  ],

  grades: {
    A: "Ready to talk",
    B: "Maybe later",
    C: "Not yet",
  },

  product: {
    id: "product",
    title: "Product",
    dataKind: "live",
    status: "ok",
    glance: "Production v269 live · staging v753 matches",
    staging: {
      id: "staging",
      name: "Staging",
      version: "v753",
      note: "Same explorer code as production right now.",
      empty: "None — staging and production match",
      gitNote: "GitHub staging is only the merge-back commit db7494dd. No open staging-only feature PRs.",
      prs: [],
    },
    production: {
      id: "production",
      name: "Production",
      version: "v269",
      live: true,
      note: "v269 live.",
      releases: [
        {
          version: "v269",
          when: "Sat Sep 12, 2026, 11:34 PM ET",
          iso: "2026-09-12T23:34:00-04:00",
          changes:
            "Chip arrows + grab-to-scroll. Admin Data Shown boxes. Narrow embed footer visible.",
        },
        {
          version: "v268",
          when: "Sun Sep 7, 2026, 11:21 AM ET",
          iso: "2026-09-07T11:21:00-04:00",
          changes: "Web workers 3→2 (memory). Not a buyer-facing feature.",
        },
        {
          version: "v267",
          when: "Fri Sep 4, 2026, 9:03 AM ET",
          iso: "2026-09-04T09:03:00-04:00",
          changes: "Motormouth MapTiler key.",
        },
      ],
    },
    schools: {
      version: "v270",
      note: "Schools production v270 — unchanged.",
    },
  },

  views: {
    dataKind: "example",
    partners: [
      { id: "realtycandy", name: "Example RealtyCandy" },
      { id: "inhouse", name: "Example in-house" },
    ],
  },

  customers: {
    id: "customers",
    title: "Customers",
    dataKind: "example",
    status: "watch",
    glance: "Everyone we know",
    directory: [
      {
        id: "west",
        name: "Example Realty — West",
        email: "west@example-realty.test",
        website: "https://west.example-realty.test",
        phone: "(555) 010-2001",
        notes: "Leftover snippet on an old embed key",
        region: "SE",
        partner: "realtycandy",
        views: 1680,
        meetings: [
          {
            id: "west-m1",
            at: "2026-09-15T10:00:00-04:00",
            who: "Myles",
            title: "Neighborhood Explorer on a listing",
          },
        ],
        thread: [
          {
            id: "west-t1",
            type: "meeting",
            at: "2026-09-10T15:00:00-04:00",
            who: "Myles",
            text: "Walked through Neighborhood Explorer on one of their listings.",
          },
          {
            id: "west-t2",
            type: "video",
            at: "2026-09-08T10:12:00-04:00",
            who: "Myles",
            text: "Sent the LocalLogic switch HeyGen video.",
          },
          {
            id: "west-t3",
            type: "email",
            at: "2026-09-08T09:40:00-04:00",
            who: "Myles",
            text: "Intro email before the video.",
          },
          {
            id: "west-t4",
            type: "call",
            at: "2026-09-05T16:20:00-04:00",
            who: "Myles",
            text: "Called about the leftover snippet on an old embed key.",
          },
        ],
      },
      {
        id: "piedmont",
        name: "Example Homes — Piedmont",
        email: "piedmont@example-homes.test",
        website: "https://piedmont.example-homes.test",
        phone: "(555) 010-2200",
        notes: "School Explorer snippet missing on the new template",
        region: "SE",
        partner: "inhouse",
        views: 920,
        meetings: [
          {
            id: "piedmont-m1",
            at: "2026-09-17T09:00:00-04:00",
            who: "Dream Neighborhood",
            title: "School Explorer snippet on the new template",
          },
        ],
        thread: [
          {
            id: "piedmont-t1",
            type: "email",
            at: "2026-09-09T11:15:00-04:00",
            who: "Myles",
            text: "They said the School Explorer snippet is missing on the new template.",
          },
          {
            id: "piedmont-t2",
            type: "video",
            at: "2026-09-06T14:05:00-04:00",
            who: "Myles",
            text: "Sent the free School Explorer upgrade video.",
          },
        ],
      },
      {
        id: "harbor",
        name: "Example Group — Harbor",
        email: "harbor@example-group.test",
        website: "https://harbor.example-group.test",
        phone: "",
        notes: "Watched the LocalLogic switch video",
        region: "NE",
        partner: "inhouse",
        views: 740,
        meetings: [],
        thread: [
          {
            id: "harbor-t1",
            type: "video",
            at: "2026-09-07T13:22:00-04:00",
            who: "Myles",
            text: "Watched the LocalLogic switch video.",
          },
          {
            id: "harbor-t2",
            type: "email",
            at: "2026-09-07T09:05:00-04:00",
            who: "Myles",
            text: "Sent the video link. No phone on file.",
          },
        ],
      },
      {
        id: "lakeside",
        name: "Example Homes — Lakeside",
        email: "lakeside@example-homes.test",
        website: "https://lakeside.example-homes.test",
        phone: "(555) 010-2500",
        notes: "On the LocalLogic list and the School Explorer upgrade list",
        region: "NE",
        partner: "inhouse",
        views: 1100,
        meetings: [],
        thread: [
          {
            id: "lakeside-t1",
            type: "email",
            at: "2026-09-08T16:40:00-04:00",
            who: "Myles",
            text: "On both the LocalLogic list and the School Explorer upgrade list.",
          },
        ],
      },
      {
        id: "oak",
        name: "Example Realty — Oak",
        email: "oak@example-realty.test",
        website: "https://oak.example-realty.test",
        phone: "(555) 010-2600",
        notes: "IDX site has no neighborhood data",
        region: "SE",
        partner: "realtycandy",
        views: 880,
        meetings: [],
        thread: [
          {
            id: "oak-t1",
            type: "email",
            at: "2026-09-04T10:18:00-04:00",
            who: "Myles",
            text: "IDX site has no neighborhood data.",
          },
        ],
      },
      {
        id: "ridge",
        name: "Example Partners — Ridge",
        email: "ridge@example-partners.test",
        website: "https://ridge.example-partners.test",
        phone: "(555) 010-2700",
        notes: "Replied after the LocalLogic video",
        region: "NE",
        partner: "inhouse",
        views: 1320,
        meetings: [
          {
            id: "ridge-m1",
            at: "2026-09-16T14:30:00-04:00",
            who: "Bill",
            title: "Follow-up after they replied",
          },
        ],
        thread: [
          {
            id: "ridge-t1",
            type: "email",
            at: "2026-09-11T08:55:00-04:00",
            who: "Example Partners — Ridge",
            text: "Replied after the LocalLogic video. Ready to talk.",
          },
          {
            id: "ridge-t2",
            type: "video",
            at: "2026-09-09T11:02:00-04:00",
            who: "Myles",
            text: "Sent the LocalLogic switch HeyGen video.",
          },
          {
            id: "ridge-t3",
            type: "call",
            at: "2026-09-03T15:10:00-04:00",
            who: "Myles",
            text: "Left a voicemail. They wrote back after the video.",
          },
        ],
      },
      {
        id: "candy",
        name: "Example Partner — Candy Lane",
        email: "candy@example-partner.test",
        website: "https://candy.example-partner.test",
        phone: "(555) 010-1000",
        notes: "RealtyCandy leftover branding on three example dashboards",
        region: "SE",
        partner: "realtycandy",
        views: 2140,
        meetings: [],
        thread: [
          {
            id: "candy-t1",
            type: "call",
            at: "2026-09-10T12:30:00-04:00",
            who: "Myles",
            text: "Talked through RealtyCandy leftover branding on three example dashboards.",
          },
          {
            id: "candy-t2",
            type: "video",
            at: "2026-09-06T09:20:00-04:00",
            who: "Myles",
            text: "Sent the free School Explorer upgrade video.",
          },
        ],
      },
      {
        id: "maple",
        name: "Example Buyer — Maple",
        email: "maple@example-buyer.test",
        website: "",
        phone: "(555) 010-2800",
        notes: "Stuck on the listing popup. Not on an outreach list.",
        region: "SE",
        partner: "realtycandy",
        views: 610,
        meetings: [],
        thread: [
          {
            id: "maple-t1",
            type: "email",
            at: "2026-09-02T17:45:00-04:00",
            who: "Dream Neighborhood",
            text: "Stuck on the listing popup. Not on an outreach list.",
          },
        ],
      },
      {
        id: "brook",
        name: "Example Homes — Brook",
        email: "brook@example-homes.test",
        website: "https://brook.example-homes.test",
        phone: "(555) 010-2900",
        notes: "Free School Explorer — replied about upgrading",
        region: "NE",
        partner: "inhouse",
        views: 780,
        meetings: [
          {
            id: "brook-m1",
            at: "2026-09-18T11:00:00-04:00",
            who: "Myles",
            title: "Upgrade from free School Explorer",
          },
        ],
        thread: [
          {
            id: "brook-t1",
            type: "email",
            at: "2026-09-12T10:08:00-04:00",
            who: "Example Homes — Brook",
            text: "Replied about upgrading from free School Explorer.",
          },
          {
            id: "brook-t2",
            type: "video",
            at: "2026-09-10T09:30:00-04:00",
            who: "Myles",
            text: "Sent the upgrade video.",
          },
        ],
      },
      {
        id: "summit",
        name: "Example Group — Summit",
        email: "summit@example-group.test",
        website: "https://summit.example-group.test",
        phone: "(555) 010-3000",
        notes: "LocalLogic office, follow-up sent",
        region: "SE",
        partner: "inhouse",
        views: 560,
        meetings: [],
        thread: [
          {
            id: "summit-t1",
            type: "email",
            at: "2026-09-11T15:16:00-04:00",
            who: "Myles",
            text: "Follow-up sent. LocalLogic office.",
          },
        ],
      },
      {
        id: "pine",
        name: "Example Realty — Pine",
        email: "pine@example-realty.test",
        website: "https://pine.example-realty.test",
        phone: "(555) 010-3100",
        notes: "IDX with no neighborhood data — replied",
        region: "NE",
        partner: "realtycandy",
        views: 1190,
        meetings: [],
        thread: [
          {
            id: "pine-t1",
            type: "email",
            at: "2026-09-12T08:12:00-04:00",
            who: "Example Realty — Pine",
            text: "Replied. IDX with no neighborhood data.",
          },
          {
            id: "pine-t2",
            type: "video",
            at: "2026-09-08T14:44:00-04:00",
            who: "Myles",
            text: "Sent the IDX neighborhood-data video.",
          },
        ],
      },
      {
        id: "vale",
        name: "Example Partners — Vale",
        email: "vale@example-partners.test",
        website: "https://vale.example-partners.test",
        phone: "(555) 010-3200",
        notes: "IDX follow-up sent",
        region: "SE",
        partner: "inhouse",
        views: 450,
        meetings: [],
        thread: [
          {
            id: "vale-t1",
            type: "email",
            at: "2026-09-09T13:50:00-04:00",
            who: "Myles",
            text: "IDX follow-up sent.",
          },
        ],
      },
      {
        id: "quarry",
        name: "Example Homes — Quarry",
        email: "quarry@example-homes.test",
        website: "https://quarry.example-homes.test",
        phone: "(555) 010-3300",
        notes: "Free School Explorer, no video yet on IDX list",
        region: "NE",
        partner: "inhouse",
        views: 390,
        meetings: [],
        thread: [
          {
            id: "quarry-t1",
            type: "note",
            at: "2026-09-06T11:00:00-04:00",
            who: "Myles",
            text: "Free School Explorer. No video yet on the IDX list.",
          },
        ],
      },
    ],
  },

  lists: {
    id: "lists",
    title: "Lists",
    dataKind: "example",
    status: "watch",
    glance: "3 example lists",
    items: [
      {
        id: "locallogic",
        name: "LocalLogic switch",
        blurb: "Offices using LocalLogic.",
        video: "Switch from LocalLogic — Neighborhood Explorer on your listings",
        members: [
          { id: "west", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "harbor", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "lakeside", videoSent: true, followupSent: true, responded: false, grade: "B", assignee: "" },
          { id: "oak", videoSent: true, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "ridge", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "brook", videoSent: false, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "summit", videoSent: true, followupSent: true, responded: false, grade: "B", assignee: "" },
        ],
      },
      {
        id: "idx",
        name: "IDX with no neighborhood data",
        blurb: "IDX sites missing neighborhood data.",
        video: "Neighborhood data on every IDX listing",
        members: [
          { id: "west", videoSent: true, followupSent: true, responded: true, grade: "B", assignee: "" },
          { id: "piedmont", videoSent: true, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "pine", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "vale", videoSent: true, followupSent: true, responded: false, grade: "B", assignee: "" },
          { id: "quarry", videoSent: false, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "oak", videoSent: true, followupSent: false, responded: false, grade: "C", assignee: "" },
        ],
      },
      {
        id: "schools-upgrade",
        name: "Free School Explorer — upgrade",
        blurb: "Free School Explorer offices that could upgrade.",
        video: "Upgrade from free School Explorer",
        members: [
          { id: "piedmont", videoSent: true, followupSent: true, responded: true, grade: "A", assignee: "" },
          { id: "lakeside", videoSent: true, followupSent: false, responded: false, grade: "B", assignee: "" },
          { id: "candy", videoSent: true, followupSent: true, responded: false, grade: "C", assignee: "" },
          { id: "brook", videoSent: true, followupSent: true, responded: true, grade: "B", assignee: "" },
          { id: "quarry", videoSent: true, followupSent: false, responded: false, grade: "C", assignee: "" },
          { id: "summit", videoSent: false, followupSent: false, responded: false, grade: "C", assignee: "" },
        ],
      },
    ],
  },

  opportunities: {
    id: "opportunities",
    title: "Opportunities",
    dataKind: "example",
    status: "watch",
    glance: "Talk to people who wrote back",
  },
};
